packages:
  - 'packages/*'
  - 'packages/plugins/*'
  - 'apps/*'
  - 'website'
  - '.'

allowBuilds:
  core-js: false
  esbuild: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vitest: 4.1.10
  vite-plus: 0.3.0
minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@0.3.0'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.3.0'
  - '@voidzero-dev/vite-plus-darwin-x64@0.3.0'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.0'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.3.0'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.3.0'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.3.0'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.0'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.3.0'
  - vite-plus@0.3.0
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
