packages:
  - 'packages/*'
  - 'packages/plugins/*'
  - 'apps/*'
  - '.'

allowBuilds:
  core-js: false
  esbuild: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.3
  vitest: 4.1.10
  vite-plus: 0.3.3
minimumReleaseAgeExclude:
  - pnpm@12.4.2
  - '@pnpm/exe.android-arm64@12.4.2'
  - '@pnpm/exe.android-x64@12.4.2'
  - '@pnpm/exe.darwin-arm64@12.4.2'
  - '@pnpm/exe.darwin-x64@12.4.2'
  - '@pnpm/exe.freebsd-x64@12.4.2'
  - '@pnpm/exe.linux-arm64@12.4.2'
  - '@pnpm/exe.linux-arm64-musl@12.4.2'
  - '@pnpm/exe.linux-ppc64@12.4.2'
  - '@pnpm/exe.linux-riscv64@12.4.2'
  - '@pnpm/exe.linux-s390x@12.4.2'
  - '@pnpm/exe.linux-x64@12.4.2'
  - '@pnpm/exe.linux-x64-musl@12.4.2'
  - '@pnpm/exe.win32-arm64@12.4.2'
  - '@pnpm/exe.win32-x64@12.4.2'
  - '@voidzero-dev/vite-plus-core@0.3.3'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.3.3'
  - '@voidzero-dev/vite-plus-darwin-x64@0.3.3'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.3'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.3.3'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.3.3'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.3.3'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.3'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.3.3'
  - vite-plus@0.3.3
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
