export const onNavigate = () => {};
export const afterNavigate = () => {};
export const beforeNavigate = () => {};
export const disableScrollHandling = () => {};
export const goto = async () => {};
export const invalidate = async () => {};
export const invalidateAll = async () => {};
export const preloadCode = async () => {};
export const preloadData = async () => {};
export const pushState = () => {};
export const replaceState = () => {};
