export {
	CalendarMonth,
	CalendarMonthFill
} from '@material-symbols-svg/svelte/icons/calendar-month';
export { Person, PersonFill } from '@material-symbols-svg/svelte/icons/person';
export { ArrowBack } from '@material-symbols-svg/svelte/icons/arrow-back';
export { EditNote } from '@material-symbols-svg/svelte/icons/edit-note';
export { ChevronRight } from '@material-symbols-svg/svelte/icons/chevron-right';
export { ListAltFill } from '@material-symbols-svg/svelte/icons/list-alt';
export { DownloadFill } from '@material-symbols-svg/svelte/icons/download';
export { IosShareFill } from '@material-symbols-svg/svelte/icons/ios-share';
export { PaletteFill } from '@material-symbols-svg/svelte/icons/palette';
export { WallpaperFill } from '@material-symbols-svg/svelte/icons/wallpaper';
export { InfoFill } from '@material-symbols-svg/svelte/icons/info';
export { Check } from '@material-symbols-svg/svelte/icons/check';
export { CheckCircleFill } from '@material-symbols-svg/svelte/icons/check-circle';
export { Edit } from '@material-symbols-svg/svelte/icons/edit';
export { CodeFill } from '@material-symbols-svg/svelte/icons/code';
export { GavelFill } from '@material-symbols-svg/svelte/icons/gavel';
export { ArticleFill } from '@material-symbols-svg/svelte/icons/article';
export { ShieldFill } from '@material-symbols-svg/svelte/icons/shield';
export { OpenInNewFill } from '@material-symbols-svg/svelte/icons/open-in-new';
export { DescriptionFill } from '@material-symbols-svg/svelte/icons/description';
export { FolderZipFill } from '@material-symbols-svg/svelte/icons/folder-zip';
export { LayersClearFill } from '@material-symbols-svg/svelte/icons/layers-clear';
export { ScheduleFill } from '@material-symbols-svg/svelte/icons/schedule';
export { EventFill } from '@material-symbols-svg/svelte/icons/event';
export { Today } from '@material-symbols-svg/svelte/icons/today';
export { CalendarToday as CalendarTodayFill } from '@material-symbols-svg/svelte/icons/calendar-today';
export { Visibility } from '@material-symbols-svg/svelte/icons/visibility';
export { VisibilityOff } from '@material-symbols-svg/svelte/icons/visibility-off';
export { AddHomeFill } from '@material-symbols-svg/svelte/icons/add-home';
export { RocketLaunchFill } from '@material-symbols-svg/svelte/icons/rocket-launch';
export { WifiOffFill } from '@material-symbols-svg/svelte/icons/wifi-off';
export { FullscreenFill } from '@material-symbols-svg/svelte/icons/fullscreen';
export { Search } from '@material-symbols-svg/svelte/icons/search';
export { Close } from '@material-symbols-svg/svelte/icons/close';
export { DeleteFill } from '@material-symbols-svg/svelte/icons/delete';
export { History } from '@material-symbols-svg/svelte/icons/history';
export { Update } from '@material-symbols-svg/svelte/icons/update';
export { Refresh } from '@material-symbols-svg/svelte/icons/refresh';
export { MobileVibrateFill } from '@material-symbols-svg/svelte/icons/mobile-vibrate';
export { TuneFill } from '@material-symbols-svg/svelte/icons/tune';
