import { writeChanged } from '../../../../../scripts/official-plugin-build/cache.ts';
import fs from 'node:fs';
import path from 'node:path';
import type { Plugin, ViteDevServer } from 'vite';
import { resolveProfile, resolveProfileId } from './profile-definitions.ts';
import { DEPLOYMENTS, resolveDeployment } from './deployment-definitions.ts';
import { OFFICIAL_PLUGINS } from '../../../../../scripts/official-plugins.config.ts';
import {
	resolveDeploymentServerPlugins,
	type ResolvedServerPlugin
} from '../../../../../scripts/official-plugin-build/server-definition.ts';
import {
	resolveOfficialMobilePlugins,
	type ResolvedMobilePlugin
} from '../../../../../scripts/official-plugin-build/mobile-server-definition.ts';

const REGISTRY_FILE = 'src/lib/boot/plugin-proxy-meta.generated.ts';
const LOADER_FILE = 'src/lib/server/plugin-server-loader.generated.ts';
const MOBILE_LOADER_FILE = 'src/lib/boot/mobile-plugin-server-registry.generated.ts';
const CATCH_ALL_ROUTE_DIR = 'src/routes/api/plugins/[pluginId]/[...action]';
const CATCH_ALL_ROUTE_FILE = `${CATCH_ALL_ROUTE_DIR}/+server.ts`;

function generateRegistrySource(plugins: ResolvedServerPlugin[]): string {
	const proxyEntries = plugins.map(
		({ id, definition }) =>
			`  { pluginId: ${JSON.stringify(id)}, action: ${JSON.stringify(definition.proxy.action)} }`
	);

	return `// Auto-generated by chronos-profile-plugin — do not edit.
export const ACTIVE_SERVER_PLUGIN_IDS = ${JSON.stringify(plugins.map((plugin) => plugin.id))} as const;

export interface PluginProxyEntry {
	pluginId: string;
	action: string;
}

export const PLUGIN_PROXY_ENTRIES: PluginProxyEntry[] = [
${proxyEntries.join(',\n')}
];

export function deploymentHasServerPlugins(): boolean {
	return ACTIVE_SERVER_PLUGIN_IDS.length > 0;
}
`;
}

function generateLoaderSource(plugins: ResolvedServerPlugin[]): string {
	const importCases = plugins
		.map(
			({ id, importPath }) =>
				`    case ${JSON.stringify(id)}:\n      return (await import(${JSON.stringify(importPath)})).serverManifest;`
		)
		.join('\n');

	return `// Auto-generated by chronos-profile-plugin — do not edit.
import type { PluginServerManifest } from '@chronos/core';

export async function loadServerManifest(pluginId: string): Promise<PluginServerManifest | null> {
	switch (pluginId) {
${importCases}
		default:
			return null;
	}
}
`;
}

const CATCH_ALL_ROUTE_SOURCE = `// Auto-generated by chronos-profile-plugin — do not edit.
import type { RequestHandler } from '@sveltejs/kit';
import { dispatchPluginRequest } from '$lib/server/plugin-proxy/dispatch';

export const config = {
	regions: ['sin1'],
	maxDuration: 60
};

export const POST: RequestHandler = (event) => dispatchPluginRequest(event, 'POST');
export const GET: RequestHandler = (event) => dispatchPluginRequest(event, 'GET');
export const PUT: RequestHandler = (event) => dispatchPluginRequest(event, 'PUT');
export const DELETE: RequestHandler = (event) => dispatchPluginRequest(event, 'DELETE');
export const HEAD: RequestHandler = (event) => dispatchPluginRequest(event, 'HEAD');
`;

function removeCatchAllRoute(webRoot: string): void {
	const routeFile = path.join(webRoot, CATCH_ALL_ROUTE_FILE);
	const routeDir = path.dirname(routeFile);
	if (fs.existsSync(routeFile)) {
		fs.unlinkSync(routeFile);
	}
	// Remove empty dirs up to api/plugins if possible
	let dir = routeDir;
	while (dir.startsWith(webRoot)) {
		if (!fs.existsSync(dir)) break;
		const entries = fs.readdirSync(dir);
		if (entries.length > 0) break;
		fs.rmdirSync(dir);
		const parent = path.dirname(dir);
		if (parent === dir) break;
		dir = parent;
	}
}

function writeCatchAllRoute(webRoot: string): void {
	const routeFile = path.join(webRoot, CATCH_ALL_ROUTE_FILE);
	fs.mkdirSync(path.dirname(routeFile), { recursive: true });
	writeChanged(routeFile, CATCH_ALL_ROUTE_SOURCE);
}

export function writeServerArtifacts(
	webRoot: string,
	activeServerPlugins: ResolvedServerPlugin[]
): void {
	const registryPath = path.join(webRoot, REGISTRY_FILE);
	const loaderPath = path.join(webRoot, LOADER_FILE);

	fs.mkdirSync(path.dirname(registryPath), { recursive: true });
	fs.mkdirSync(path.dirname(loaderPath), { recursive: true });
	writeChanged(registryPath, generateRegistrySource(activeServerPlugins));
	writeChanged(loaderPath, generateLoaderSource(activeServerPlugins));

	if (activeServerPlugins.length > 0) {
		writeCatchAllRoute(webRoot);
	} else {
		removeCatchAllRoute(webRoot);
	}
}

export function writeMobileServerArtifacts(webRoot: string, plugins: ResolvedMobilePlugin[]): void {
	const target = path.join(webRoot, MOBILE_LOADER_FILE);
	const imports = plugins
		.map(
			({ importPath }, index) =>
				`import { mobilePluginServerModule as module${index} } from ${JSON.stringify(importPath)};`
		)
		.join('\n');
	const registrations = plugins
		.map(
			({ definition }, index) =>
				`\t{\n\t\tdefinition: ${JSON.stringify(definition)},\n` +
				`\t\tcreateHandlers: (context) => module${index}.createHandlers(context)\n\t}`
		)
		.join(',\n');
	const source = `// Auto-generated by chronos-profile-plugin — do not edit.
import type { IHostHttpSessionService } from '@chronos/core';
import { createMobilePluginServerRegistry } from '../../../../mobile/src/http/mobile-plugin-server-registry';
${imports}

export function createGeneratedMobilePluginServerRegistry(sessions: IHostHttpSessionService) {
	return createMobilePluginServerRegistry([
${registrations}
	], sessions);
}
`;
	fs.mkdirSync(path.dirname(target), { recursive: true });
	writeChanged(target, source);
}

export interface EmitProfileArtifactsOptions {
	profileId?: string;
	deploymentId?: string;
	repositoryRoot?: string;
}

export async function emitProfileArtifacts(
	webRoot: string,
	options?: EmitProfileArtifactsOptions
): Promise<void> {
	const profileId = options?.profileId ?? resolveProfileId();
	const profile = resolveProfile(profileId);
	for (const entry of profile.preinstall) {
		if (!OFFICIAL_PLUGINS.some((plugin) => plugin.id === entry.id))
			throw new Error(`Unknown preinstall plugin: ${entry.id}`);
	}
	const deploymentId = options?.deploymentId;
	const deploymentDef = deploymentId
		? (DEPLOYMENTS[deploymentId] ?? resolveDeployment({ CHRONOS_DEPLOYMENT: deploymentId }))
		: resolveDeployment();
	const repoRoot = options?.repositoryRoot ?? path.resolve(webRoot, '../..');
	const activeServerPlugins = await resolveDeploymentServerPlugins(
		deploymentDef.serverPlugins,
		repoRoot
	);
	const denied = profile.deniedPluginServerActions ?? [];
	writeServerArtifacts(
		webRoot,
		activeServerPlugins.filter(
			(p) => !denied.some((d) => d.pluginId === p.id && d.action === p.definition.proxy.action)
		)
	);
	const mobilePlugins = await resolveOfficialMobilePlugins(repoRoot);
	writeMobileServerArtifacts(
		webRoot,
		mobilePlugins.filter(
			(p) => !denied.some((d) => d.pluginId === p.id && p.definition.actions.includes(d.action))
		)
	);
}

export function chronosProfilePlugin(webRoot: string): Plugin {
	const pluginsRoot = path.resolve(webRoot, '../../packages/plugins');
	let refreshPending: Promise<void> = Promise.resolve();
	const refreshDefinition = (filePath: string, server: ViteDevServer) => {
		const relativePath = path.relative(pluginsRoot, filePath).replace(/\\/g, '/');
		if (
			!/^[^/]+\/(?:package\.json|server\/definition\.ts|src\/mobile\/(?:index|definition)\.ts)$/.test(
				relativePath
			)
		)
			return;
		refreshPending = refreshPending
			.then(async () => {
				await emitProfileArtifacts(webRoot);
				server.ws.send({ type: 'full-reload' });
			})
			.catch((error: unknown) => server.config.logger.error(String(error)));
	};
	return {
		name: 'chronos-profile',
		async configureServer(server) {
			await emitProfileArtifacts(webRoot);
			server.watcher.add(pluginsRoot);
			server.watcher.on('change', (filePath) => refreshDefinition(filePath, server));
			server.watcher.on('add', (filePath) => refreshDefinition(filePath, server));
			server.watcher.on('unlink', (filePath) => refreshDefinition(filePath, server));
		},
		async buildStart() {
			await emitProfileArtifacts(webRoot);
		}
	};
}
