import fs from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';
import {
	SERVER_PLUGIN_MODULES,
	CLIENT_BUILTIN_PLUGIN_MODULES,
	resolveActiveBuiltinPluginIds,
	resolveActiveServerPluginIds,
	resolveProfileId
} from './profile-definitions.ts';

const REGISTRY_FILE = 'src/lib/boot/plugin-proxy-meta.generated.ts';
const AVAILABLE_PLUGINS_FILE = 'src/lib/boot/available-plugins.generated.ts';
const LOADER_FILE = 'src/lib/server/plugin-server-loader.generated.ts';
const CATCH_ALL_ROUTE_DIR = 'src/routes/api/plugins/[pluginId]/[...action]';
const CATCH_ALL_ROUTE_FILE = `${CATCH_ALL_ROUTE_DIR}/+server.ts`;

function generateRegistrySource(activePluginIds: string[]): string {
	const proxyEntries = activePluginIds
		.map((id) => {
			const mod = SERVER_PLUGIN_MODULES[id];
			if (!mod) return null;
			return `  { pluginId: '${id}', domains: ${JSON.stringify(mod.domains)}, action: '${mod.action}' }`;
		})
		.filter(Boolean);

	return `// Auto-generated by chronos-profile-plugin — do not edit.
export const ACTIVE_SERVER_PLUGIN_IDS = ${JSON.stringify(activePluginIds)} as const;

export interface PluginProxyEntry {
	pluginId: string;
	domains: string[];
	action: string;
}

export const PLUGIN_PROXY_ENTRIES: PluginProxyEntry[] = [
${proxyEntries.join(',\n')}
];

export function profileHasServerPlugins(): boolean {
	return ACTIVE_SERVER_PLUGIN_IDS.length > 0;
}
`;
}

function generateAvailablePluginsSource(activeBuiltinPluginIds: string[]): string {
	const importLines = new Map<string, string>();
	const pluginRefs: string[] = [];

	for (const id of activeBuiltinPluginIds) {
		const mod = CLIENT_BUILTIN_PLUGIN_MODULES[id];
		if (!mod) continue;
		const importLine = `import { ${mod.exportName} } from '${mod.importPath}';`;
		importLines.set(mod.importPath, importLine);
		pluginRefs.push(`${mod.exportName} as unknown as ChronosPlugin`);
	}

	return `// Auto-generated by chronos-profile-plugin — do not edit.
import type { ChronosPlugin } from '@chronos/core';
${[...importLines.values()].join('\n')}

export const availablePlugins: readonly ChronosPlugin[] = [
\t${pluginRefs.join(',\n\t')}
];
`;
}

function generateLoaderSource(activePluginIds: string[]): string {
	const importCases = activePluginIds
		.map((id) => {
			const mod = SERVER_PLUGIN_MODULES[id];
			if (!mod) return '';
			return `    case '${id}':\n      return (await import('${mod.importPath}')).serverManifest;`;
		})
		.join('\n');

	return `// Auto-generated by chronos-profile-plugin — do not edit.
export async function loadServerManifest(pluginId: string) {
	switch (pluginId) {
${importCases}
		default:
			return null;
	}
}
`;
}

const CATCH_ALL_ROUTE_SOURCE = `// Auto-generated by chronos-profile-plugin — do not edit.
import type { RequestHandler } from '@sveltejs/kit';
import { dispatchPluginRequest } from '$lib/server/plugin-proxy/dispatch';

export const config = {
	regions: ['sin1'],
	maxDuration: 60
};

export const POST: RequestHandler = (event) => dispatchPluginRequest(event, 'POST');
export const GET: RequestHandler = (event) => dispatchPluginRequest(event, 'GET');
export const PUT: RequestHandler = (event) => dispatchPluginRequest(event, 'PUT');
export const DELETE: RequestHandler = (event) => dispatchPluginRequest(event, 'DELETE');
export const HEAD: RequestHandler = (event) => dispatchPluginRequest(event, 'HEAD');
`;

function removeCatchAllRoute(webRoot: string): void {
	const routeFile = path.join(webRoot, CATCH_ALL_ROUTE_FILE);
	const routeDir = path.dirname(routeFile);
	if (fs.existsSync(routeFile)) {
		fs.unlinkSync(routeFile);
	}
	// Remove empty dirs up to api/plugins if possible
	let dir = routeDir;
	while (dir.startsWith(webRoot)) {
		if (!fs.existsSync(dir)) break;
		const entries = fs.readdirSync(dir);
		if (entries.length > 0) break;
		fs.rmdirSync(dir);
		const parent = path.dirname(dir);
		if (parent === dir) break;
		dir = parent;
	}
}

function writeCatchAllRoute(webRoot: string): void {
	const routeFile = path.join(webRoot, CATCH_ALL_ROUTE_FILE);
	fs.mkdirSync(path.dirname(routeFile), { recursive: true });
	fs.writeFileSync(routeFile, CATCH_ALL_ROUTE_SOURCE, 'utf8');
}

function emitProfileArtifacts(webRoot: string): void {
	const profileId = resolveProfileId();
	const activeServerPluginIds = resolveActiveServerPluginIds(profileId);
	const activeBuiltinPluginIds = resolveActiveBuiltinPluginIds(profileId);
	const registryPath = path.join(webRoot, REGISTRY_FILE);
	const availablePluginsPath = path.join(webRoot, AVAILABLE_PLUGINS_FILE);
	const loaderPath = path.join(webRoot, LOADER_FILE);

	fs.mkdirSync(path.dirname(registryPath), { recursive: true });
	fs.writeFileSync(registryPath, generateRegistrySource(activeServerPluginIds), 'utf8');
	fs.writeFileSync(
		availablePluginsPath,
		generateAvailablePluginsSource(activeBuiltinPluginIds),
		'utf8'
	);
	fs.writeFileSync(loaderPath, generateLoaderSource(activeServerPluginIds), 'utf8');

	if (activeServerPluginIds.length > 0) {
		writeCatchAllRoute(webRoot);
	} else {
		removeCatchAllRoute(webRoot);
	}
}

export function chronosProfilePlugin(webRoot: string): Plugin {
	return {
		name: 'chronos-profile',
		configureServer() {
			emitProfileArtifacts(webRoot);
		},
		buildStart() {
			emitProfileArtifacts(webRoot);
		}
	};
}

export { emitProfileArtifacts };
